### ISSUE TITLE
NRCS AGOL awdb sites descriptions 

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/awdb-retrieve#3]
Most awdb sites feature layers on NRCS AGOL don't have a description. The description for SNOW is incorrect. Are these feature layers republished when the awdb retrieval script is executed? If so, then we need to update the service definition files to include the layer descriptions. If the script just updates the data without republishing the feature layers, then we could manually update the descriptions.

Here are the layer descriptions.

stations_BOR_ACTIVE: Active Bureau of Reclamation reservoir stations plus other non-BOR reservoir stations
stations_COOP_ACTIVE: Active National Weather Service COOP stations
stations_MPRC_ACTIVE: Active Manual precipitation sites
stations_MSNT_ACTIVE: Active Manual SNOTEL non-telemetered, non-real time sites
stations_OTHER_ACTIVE: Active other sites
stations_SCAN_ACTIVE: Active Soil Climate Analysis Network (SCAN) sites
stations_SNOW_ACTIVE: Active NRCS snow course sites
stations_SNTL_ACTIVE: Active NWCC SNOTEL (for SNOw TELemetry) sites
stations_SNTLT_ACTIVE: Active NWCC SNOTEL Lite sites
stations_USGS_ACTIVE: Active USGS station, but also other non-USGS streamflow stations

**Comment by lbross** [comment]
I just spot-checked a few of these on NRCS AGOL and it looks like someone added the descriptions. The layers also have today's date as the last updated date. The script should update the data without republishing the feature layers so these new descriptions should "stick". The script runs on Tuesday nights so I will check the descriptions tomorrow to make sure they are still in place.

**Comment by jdduh** [comment]
Thanks for the confirmation. I edited the descriptions earlier. NWCC starts sharing these layers with their collaborators and needs the information to be accurate.

**Comment by lbross** [comment]
Unfortunately the descriptions did not "stick". I'm not sure where it is pulling them from because they aren't null, just different from what you posted yesterday. I am looking into it.

**Comment by lbross** [comment]
This is done. It is possible to update the summary and item description from the web client, but you have to update the sd file, not the layer itself. The sd files for these services are all in the awdb_sd folder. I will make a note to check this one more time, just in case, after the service data is updated next Tuesday
