### ISSUE TITLE
Awdb webservices server

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/awdb-retrieve#6]
It seems that NRCS ArcGIS Online is the server for awdb station feature services. Can we remove the awdb services on basins?
Here are the awdb services on basins.

awdb active: http://webservices.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE
awdb all: http://webservices.geog.pdx.edu/arcgis/rest/services/AWDB_ALL
awdb inactive: http://webservices.geog.pdx.edu/arcgis/rest/services/AWDB_INACTIVE

**Comment by lbross** [comment]
This is up to you @jdduh. The BAGIS Pro batch tool is using the awdb services on AGOL. And it looks like the default basinanalyst.def has also been updated to use the AGOL services. Clients with an old basinanalyst.def could potentially still be pointed at the basins services. They would need to update these locations. I'm not sure what other clients might be pointed at the basins services?
There are no _ALL or _INACTIVE services on AGOL. I don't know if this is a problem?

**Comment by lbross** [comment]
Closing. The awdb services have been turned off on basins since the Windows upgrade.
